[package]
name = "rudric"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio", "migrate"] }
tokio = { version = "1.35.0", features = ["macros", "rt-multi-thread"] }
orion = { version = "0.17.6", features = ["serde"] }
xdg = "2.5.2"
dialoguer = "0.11.0"
